### ISSUE TITLE
Criar página de 'Sobre'

### ISSUE THREAD

**Issue by TalesMattos** [mtales/github-master#3]
mtales, aqui é TalesMattos! Você poderia criar uma página de 'sobre'?

**Comment by mtales** [comment]
A página já está no forno em desenvolvimento

**Comment by TalesMattos** [comment]
Obrigado, estou aguardando

Em seg, 12 de ago de 2019 21:43, Tales Mattos <notifications@github.com>
escreveu:

**Comment by TalesMattos** [comment]
Ficou do balaco-baco
